import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

import {
    convert,
    currencySymbol,
    formatCompactCurrencyDisplay,
    formatCurrencyDisplay,
    formatCurrencyNumber,
    format,
    sumFormatted,
} from '../../resources/js/lib/money.ts';

/**
 * Ground truth generated by the PHP CurrencyConverter. The same file is asserted
 * by tests/Feature/CurrencyConverterTest.php, so if either implementation drifts
 * both suites fail and name the exact case.
 */
const vectors = JSON.parse(
    readFileSync(
        new URL('../fixtures/money-vectors.json', import.meta.url),
        'utf8',
    ),
);

const rates = vectors.rates;

test('every conversion matches the server', () => {
    assert.ok(vectors.conversions.length > 0);

    for (const vector of vectors.conversions) {
        assert.equal(
            format(vector.amount, vector.from, vector.to, rates),
            vector.expected,
            `${vector.amount} ${vector.from} -> ${vector.to}`,
        );
    }
});

test('multi-currency totals match the server', () => {
    for (const vector of vectors.sums) {
        assert.equal(
            sumFormatted(vector.items, vector.target, rates),
            vector.expected,
            `sum -> ${vector.target}`,
        );
    }
});

test('an identical currency pair is a no-op beyond rounding', () => {
    assert.equal(convert('1500000', 'toman', 'toman', rates), 1500000);
    assert.equal(format('42', 'eur', 'eur', rates), '42.00');
});

test('missing rates yield zero rather than Infinity or NaN', () => {
    const dead = { tomanPerUsd: 0, tomanPerEur: 0 };

    assert.equal(convert(1, 'usd', 'toman', dead), 0);
    assert.equal(convert(1500000, 'toman', 'usd', dead), 0);
    assert.equal(convert(10, 'eur', 'usd', dead), 0);
    assert.equal(format(10, 'usd', 'eur', dead), '0.00');
});

test('rounding breaks ties away from zero, as PHP does', () => {
    // Same currency, so this exercises round2 directly.
    assert.equal(convert('1.005', 'usd', 'usd', rates), 1.01);
    assert.equal(convert('-1.005', 'usd', 'usd', rates), -1.01);
});

test('a non-numeric amount is treated as zero rather than NaN', () => {
    assert.equal(convert('', 'usd', 'usd', rates), 0);
    assert.equal(format('nonsense', 'usd', 'toman', rates), '0.00');
});

test('currency symbols keep their financial reading order', () => {
    assert.equal(formatCurrencyDisplay('1,250', 'toman'), '1,250\u00a0T');
    assert.equal(formatCurrencyDisplay('8.50', 'usd'), '$8.50');
    assert.equal(formatCurrencyDisplay('7.25', 'eur'), '€7.25');
    assert.equal(formatCurrencyDisplay('-1250', 'usd'), '($1,250.00)');
    assert.equal(formatCurrencyDisplay('-1250', 'eur'), '(€1,250.00)');
    assert.equal(formatCurrencyDisplay('-1250', 'toman'), '(1,250\u00a0T)');
    assert.equal(currencySymbol('toman'), 'T');
});

test('currency precision follows the selected unit', () => {
    assert.equal(formatCurrencyNumber('1250.49', 'toman'), '1,250');
    assert.equal(formatCurrencyNumber('1250', 'usd'), '1,250.00');
    assert.equal(formatCurrencyNumber('1250.5', 'eur'), '1,250.50');
    assert.equal(formatCurrencyNumber('-1250.5', 'eur'), '(1,250.50)');
});

test('compact currency values retain symbol and sign order', () => {
    assert.equal(
        formatCompactCurrencyDisplay('1250000', 'toman'),
        '1.3M\u00a0T',
    );
    assert.equal(formatCompactCurrencyDisplay('1250', 'usd'), '$1.3K');
    assert.equal(formatCompactCurrencyDisplay('-1250', 'usd'), '($1.3K)');
    assert.equal(formatCompactCurrencyDisplay('-1250', 'eur'), '(€1.3K)');
    assert.equal(
        formatCompactCurrencyDisplay('-1250000', 'toman'),
        '(1.3M\u00a0T)',
    );
});

test('a Persian locale renders Persian digits, symbol and sign order intact', () => {
    assert.equal(
        formatCurrencyDisplay('1250000', 'toman', 'fa-IR'),
        '\u06f1\u066c\u06f2\u06f5\u06f0\u066c\u06f0\u06f0\u06f0\u00a0T',
    );
    assert.equal(
        formatCurrencyDisplay('-1250000', 'toman', 'fa-IR'),
        '(\u06f1\u066c\u06f2\u06f5\u06f0\u066c\u06f0\u06f0\u06f0\u00a0T)',
    );
    assert.equal(
        formatCurrencyDisplay('-8.5', 'usd', 'fa-IR'),
        '($\u06f8\u066b\u06f5\u06f0)',
    );
    // fa-IR own compact form spells out the magnitude rather than using a
    // K/M suffix, still Persian digits, still accounting parens.
    assert.equal(
        formatCompactCurrencyDisplay('1250000', 'toman', 'fa-IR'),
        '\u06f1\u066b\u06f3\u00a0\u0645\u06cc\u0644\u06cc\u0648\u0646\u00a0T',
    );
    assert.equal(
        formatCompactCurrencyDisplay('-1250000', 'toman', 'fa-IR'),
        '(\u06f1\u066b\u06f3\u00a0\u0645\u06cc\u0644\u06cc\u0648\u0646\u00a0T)',
    );
});
